apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: backenddb
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
      app.kubernetes.io/component: backenddb
  replicas: 3 
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
        app.kubernetes.io/component: backenddb
    spec:
      containers:
      - name: backenddb
        image: 756055132391.dkr.ecr.us-east-1.amazonaws.com/kindclusterdb:clo835-db
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: db_pass123
        - name: DBHOST
          value: mysqldb
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
