apiVersion: v1
kind: Pod
metadata:
  name: gcmsdb
spec:
  containers:
  - name: gcmsdb
    image: 756055132391.dkr.ecr.us-east-1.amazonaws.com/kindclusterdb:clo835-db
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: db_pass123
    - name: DBPORT
      value: "3306"
    resources:
      requests:
        cpu: 100m
        memory: 100Mi