apiVersion: apps/v1
kind: Deployment
metadata:
  name: primaryend
  labels:
    app.kubernetes.io/name: employees
    app.kubernetes.io/component: primaryend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: employees
      app.kubernetes.io/component: primaryend
  replicas: 3 
  template:
    metadata:
      labels:
        app.kubernetes.io/name: employees
        app.kubernetes.io/component: primaryend
    spec:
      containers:
      - name: primaryend
        image: 756055132391.dkr.ecr.us-east-1.amazonaws.com/kindclusterapp:clo835-app
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "0.0.0.0"
        - name: DBPORT
          value: "3306"
        - name: DBPWD
          value: "db_pass123"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi 
        