apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: gcmswebapp
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: gcmswebapp
        image: 756055132391.dkr.ecr.us-east-1.amazonaws.com/kindclusterapp:clo835-app
        ports:
        - containerPort: 3306
        env:
        - name: DBHOST
          value: "mysql.globe.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBPWD
          value: "db_pass123" 
        resources:
          requests:
            cpu: 100m
            memory: 100Mi