apiVersion: v1
kind: Service
metadata:
  name: gcmswebapp
  labels:
    app: employees
spec:
  type: NodePort
  externalName: mysql.globe.svc.cluster.local  
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:
    app: employees